### ISSUE TITLE
residuals are not finite in the initial point

### ISSUE THREAD

**Issue by samlipworth** [johnlees/PopPUNK#37]
Hi John,

I'm getting the following issue running on ~ 3000 E. coli assemblies (which all look reasonable from a QC perspective).  I previously managed to run poppunk with no issues but had to reinstall conda and hence poppunk and since then I can't get it to work.  Do you have any idea what the issue is?

Traceback (most recent call last):
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 757, in map
    capsule = pg.get(R)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 429, in get
    raise StopProcessGroup
sharedmem.sharedmem.StopProcessGroup: StopProcessGroup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/miniconda3/bin/poppunk", line 11, in <module>
    sys.exit(main())
  File "/home/sam/miniconda3/lib/python3.6/site-packages/PopPUNK/__main__.py", line 210, in main
    args.plot_fit, args.no_stream, args.mash, args.threads)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/PopPUNK/mash.py", line 520, in queryDatabase
    pool.map(partial(fitKmerBlock, distMat=distMat, raw = raw, klist=klist, jacobian=jacobian), mat_chunks)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 761, in map
    raise pg.get_exception()
sharedmem.sharedmem.SlaveException: Residuals are not finite in the initial point.
Traceback (most recent call last):
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 294, in _slaveMain
    self.main(self, *self.args)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 628, in _main
    r = realfunc(work)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/sharedmem/sharedmem.py", line 703, in realfunc
    else: return func(i)
  File "/home/sam/miniconda3/lib/python3.6/site-packages/PopPUNK/mash.py", line 543, in fitKmerBlock
    distMat[start:end, :] = np.apply_along_axis(fitKmerCurve, 1, raw[start:end, :], klist, jacobian)
  File "/home/sam/.local/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 380, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "/home/sam/miniconda3/lib/python3.6/site-packages/PopPUNK/mash.py", line 570, in fitKmerCurve
    bounds=([-np.inf, -np.inf], [0, 0]))
  File "/home/sam/.local/lib/python3.6/site-packages/scipy/optimize/_lsq/least_squares.py", line 805, in least_squares
    raise ValueError("Residuals are not finite in the initial point.")
ValueError: Residuals are not finite in the initial point.

**Comment by nickjcroucher** [comment]
Hi Sam,

Looks like the curve fitting is failing - would you mind sharing the command line you ran this with, and performing a run with "--plot-fit 20" to generate some sample graphs to look at what might be causing the problem? If you subsample to a small set 20 or so genomes, does it complete - in case that helps narrow whether there's a few problematic sequnces?
