### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by vaofford** [johnlees/PopPUNK#39]
Hi John,

We're getting some dependency errors after installing with pip (below).  Using gcc-4.8.1 seemed to fix it for us.

Hope this helps!

Victoria 
Pathogen Informatics 

**poppunk -h**
Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 119, in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, _lib_name))
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by /software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/llvmlite/binding/libllvmlite.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/bin/poppunk", line 11, in <module>
    load_entry_point('poppunk==1.1.3', 'console_scripts', 'poppunk')()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/PopPUNK/__main__.py", line 23, in <module>
    from .models import *
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/PopPUNK/models.py", line 35, in <module>
    from .refine import refineFit
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/PopPUNK/refine.py", line 11, in <module>
    from numba import jit
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numba/__init__.py", line 10, in <module>
    from . import config, errors, runtests, types
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/llvmlite/binding/ffi.py", line 124, in <module>
    lib = ctypes.CDLL(_lib_name)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libllvmlite.so: cannot open shared object file: No such file or directory

**Comment by johnlees** [comment]
Ah, thanks! I'll note this in the installation instructions

**Comment by johnlees** [comment]
Closed by 89baa18dcd8edaca9dbfffc80026ca9ab478918c
