### ISSUE TITLE
Multiple errors when running --assign-query

### ISSUE THREAD

**Issue by WouterVork** [johnlees/PopPUNK#52]
Hello,

I'm trying to assign some queries to a reference database which I downloaded from poppunk.net, but I am getting multiple errors:
```
poppunk --assign-query --ref-db listeria_references --distances listeria_references/listeria_references.dists --model-dir listeria_references --q-files listerias.txt --output listeria-ref_db --threads 8
/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
Mode: Assigning clusters of query sequences

Creating mash database for k = 13
Random 13-mer probability: 0.04
Creating mash database for k = 15
Random 15-mer probability: 0.00
Creating mash database for k = 17
Random 17-mer probability: 0.00
Creating mash database for k = 19
Random 19-mer probability: 0.00
Creating mash database for k = 21
Random 21-mer probability: 0.00
Creating mash database for k = 23
Random 23-mer probability: 0.00
Creating mash database for k = 25
Random 25-mer probability: 0.00
Creating mash database for k = 27
Random 27-mer probability: 0.00
Creating mash database for k = 29
Random 29-mer probability: 0.00
mash dist -p 8 listeria_references/listeria_references.13.msh listeria-ref_db/listeria-ref_db.13.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.15.msh listeria-ref_db/listeria-ref_db.15.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.17.msh listeria-ref_db/listeria-ref_db.17.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.19.msh listeria-ref_db/listeria-ref_db.19.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.21.msh listeria-ref_db/listeria-ref_db.21.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.23.msh listeria-ref_db/listeria-ref_db.23.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.25.msh listeria-ref_db/listeria-ref_db.25.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.27.msh listeria-ref_db/listeria-ref_db.27.msh 2> listeria_references.err.log
mash dist -p 8 listeria_references/listeria_references.29.msh listeria-ref_db/listeria-ref_db.29.msh 2> listeria_references.err.log
Calculating core and accessory distances
/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator BayesianGaussianMixture from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Loading BGMM 2D Gaussian model
Network loaded: 31 samples
Found novel query clusters. Calculating distances between them:
Creating mash database for k = 13
Random 13-mer probability: 0.03
Creating mash database for k = 15
Random 15-mer probability: 0.00
Creating mash database for k = 17
Random 17-mer probability: 0.00
Creating mash database for k = 19
Random 19-mer probability: 0.00
Creating mash database for k = 21
Random 21-mer probability: 0.00
Creating mash database for k = 23
Random 23-mer probability: 0.00
Creating mash database for k = 25
Random 25-mer probability: 0.00
Creating mash database for k = 27
Random 27-mer probability: 0.00
Creating mash database for k = 29
Random 29-mer probability: 0.00
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.13.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.13.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.15.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.15.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.17.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.17.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.19.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.19.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.21.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.21.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.23.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.23.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.25.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.25.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.27.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.27.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
mash dist -p 8 ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.29.msh ./listeria-ref_dbvu69dr0x_tmp/listeria-ref_dbvu69dr0x_tmp.29.msh 2> listeria-ref_dbvu69dr0x_tmp.err.log
Calculating core and accessory distances
Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 415, in get
    return Q.get(timeout=1)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 423, in get
    return Q.get(timeout=0)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 757, in map
    capsule = pg.get(R)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 425, in get
    raise StopProcessGroup
sharedmem.sharedmem.StopProcessGroup: StopProcessGroup

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/bin/poppunk", line 10, in <module>
    sys.exit(main())
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/PopPUNK/__main__.py", line 388, in main
    args.rapidnj, args.perplexity)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/PopPUNK/__main__.py", line 539, in assign_query
    threads, mash)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/PopPUNK/network.py", line 346, in addQueryToNetwork
    0, no_stream, mash_exec = mash_exec, threads = threads)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/PopPUNK/mash.py", line 575, in queryDatabase
    pool.map(partial(fitKmerBlock, distMat=distMat, raw = raw, klist=klist, jacobian=jacobian), mat_chunks)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 761, in map
    raise pg.get_exception()
sharedmem.sharedmem.SlaveException: Cannot apply_along_axis when any iteration dimensions are 0
Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 376, in apply_along_axis
    ind0 = next(inds)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 294, in _slaveMain
    self.main(self, *self.args)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 628, in _main
    r = realfunc(work)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/sharedmem/sharedmem.py", line 703, in realfunc
    else: return func(i)
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/PopPUNK/mash.py", line 598, in fitKmerBlock
    distMat[start:end, :] = np.apply_along_axis(fitKmerCurve, 1, raw[start:end, :], klist, jacobian)
  File "<__array_function__ internals>", line 6, in apply_along_axis
  File "/home/admin_bi/Documents/Software/Miniconda/envs/poppunk/lib/python3.7/site-packages/numpy/lib/shape_base.py", line 378, in apply_along_axis
    raise ValueError('Cannot apply_along_axis when any iteration dimensions are 0')
ValueError: Cannot apply_along_axis when any iteration dimensions are 0
```
I tried this in a fresh conda environment in which only poppunk was installed by doing ``` conda install poppunk ```

**Comment by johnlees** [comment]
I'm not sure why this is happening. Would you be able to share the genomes
you're trying to assign so I can try and replicate the error?

Could you also try running with a single thread, and with the `--full-db`
option?

Cheers,
John

**Comment by WouterVork** [comment]
Hello John,

Here is a Google Drive link with the genomes: [](https://drive.google.com/file/d/1BYSW_ZV6EB29ip0dS1-eYjeqx-1TvlHV/view?usp=sharing)

Running the same command with a single thread and the `--full-db` option didn't give me any errors.

**Comment by johnlees** [comment]
I couldn't replicate this on my machine, using exactly the same data and run. I think this is probably related to the threading, but I'n not exactly sure how. I would suggest either re-running, or reducing the number of threads if encountering this error
(my previous suggestion of `--full-db` isn't necessary)
