### ISSUE TITLE
Overwriting some sketches only

### ISSUE THREAD

**Issue by nickjcroucher** [johnlees/PopPUNK#66]
Writing to the same directory with "--overwrite", but altered k-mer sets, generates an error message:

```
Traceback (most recent call last):
  File "./PopPUNK/poppunk-runner.py", line 10, in <module>
    main()
  File "PopPUNK/__main__.py", line 262, in main
    createDatabaseDir(args.output, kmers)
  File "PopPUNK/sketchlib.py", line 75, in createDatabaseDir
    if not (kmers == knum).any():
AttributeError: 'bool' object has no attribute 'any'
```

The offending code in sketchlib.py:

```
                if not (kmers == knum).any():
                    sys.stderr.write("Removing old database " + db_file + "\n")
                    sys.stderr.write("(k-mer size " + str(knum) +
                                    " not in requested range " + str(knum) + ")\n")
                    os.remove(db_file)
```

Problem is that two lists are being compared, whereas it seems we want to check individual values against one list?

**Comment by nickjcroucher** [comment]
OK, fix is non-Pythonic again (756f111abfe302f3ebaa9bd6241cbd1cc0e579a1):

 ```
               knum = ref_db['sketches/' + sample_name].attrs['kmers']
                remove_prev_db = False
                for kmer_length in knum:
                    if not (kmers == kmer_length).any():
                        sys.stderr.write("Previously-calculated k-mer size " + str(kmer_length) +
                                        " not in requested range (" + str(knum) + ")\n")
                        remove_prev_db = True
                        break
                if remove_prev_db:
                    sys.stderr.write("Removing old database " + db_file + "\n")
                    os.remove(db_file)
                    break
```
